import 'package:flutter/material.dart';

import 'codemirror/impl.dart';
import 'codemirror/io.dart' if (dart.library.html) 'codemirror/web.dart';

export 'codemirror/impl.dart';

class Editor extends StatelessWidget {
  Editor({
    Key? key,
    required this.onCreate,
    required this.onValue,
    required this.options,
    this.codeMirrorKey,
  }) : super(key: key) {}

  final CodeMirrorOptions options;
  final ValueChanged<EditorController> onCreate;
  final void Function(String val) onValue;
  final Key? codeMirrorKey;

  static List<String> MODES = const <String>[
    "apl",
    "gfm",
    "ntriples",
    "spreadsheet",
    "asciiarmor",
    "gherkin",
    "octave",
    "sql",
    "asn.1",
    "go",
    "oz",
    "stex",
    "asterisk",
    "groovy",
    "pascal",
    "stylus",
    "brainfuck",
    "haml",
    "pegjs",
    "swift",
    "clike",
    "handlebars",
    "perl",
    "tcl",
    "clojure",
    "haskell",
    "php",
    "textile",
    "cmake",
    "haskell-literate",
    "pig",
    "tiddlywiki",
    "cobol",
    "haxe",
    "powershell",
    "tiki",
    "coffeescript",
    "htmlembedded",
    "properties",
    "toml",
    "commonlisp",
    "htmlmixed",
    "protobuf",
    "tornado",
    "crystal",
    "http",
    "pug",
    "troff",
    "css",
    "idl",
    "puppet",
    "ttcn",
    "cypher",
    "index.html",
    "python",
    "ttcn-cfg",
    "d",
    "javascript",
    "q",
    "turtle",
    "dart",
    "jinja2",
    "r",
    "twig",
    "diff",
    "jsx",
    "rpm",
    "vb",
    "django",
    "julia",
    "rst",
    "vbscript",
    "dockerfile",
    "livescript",
    "ruby",
    "velocity",
    "dtd",
    "lua",
    "rust",
    "verilog",
    "dylan",
    "markdown",
    "sas",
    "vhdl",
    "ebnf",
    "mathematica",
    "sass",
    "vue",
    "ecl",
    "mbox",
    "scheme",
    "wast",
    "eiffel",
    "meta.js",
    "shell",
    "webidl",
    "elm",
    "mirc",
    "sieve",
    "xml",
    "erlang",
    "mllike",
    "slim",
    "xquery",
    "factor",
    "modelica",
    "smalltalk",
    "yacas",
    "fcl",
    "mscgen",
    "smarty",
    "yaml",
    "forth",
    "mumps",
    "solr",
    "yaml-frontmatter",
    "fortran",
    "nginx",
    "soy",
    "z80",
    "gas",
    "nsis",
    "sparql",
  ];

  static final List<String> THEMES = const [
    '3024-day',
    '3024-night',
    'abcdef',
    'ambiance-mobile',
    'ambiance',
    'ayu-dark',
    'ayu-mirage',
    'base16-dark',
    'base16-light',
    'bespin',
    'blackboard',
    'cobalt',
    'colorforth',
    'darcula',
    'dracula',
    'duotone-dark',
    'duotone-light',
    'eclipse',
    'elegant',
    'erlang-dark',
    'gruvbox-dark',
    'hopscotch',
    'icecoder',
    'idea',
    'isotope',
    'lesser-dark',
    'liquibyte',
    'lucario',
    'material-darker',
    'material-ocean',
    'material-palenight',
    'material',
    'mbo',
    'mdn-like',
    'midnight',
    'monokai',
    'moxer',
    'neat',
    'neo',
    'night',
    'nord',
    'oceanic-next',
    'panda-syntax',
    'paraiso-dark',
    'paraiso-light',
    'pastel-on-dark',
    'railscasts',
    'rubyblue',
    'seti',
    'shadowfox',
    'solarized',
    'ssms',
    'the-matrix',
    'tomorrow-night-bright',
    'tomorrow-night-eighties',
    'ttcn',
    'twilight',
    'vibrant-ink',
    'xq-dark',
    'xq-light',
    'yeti',
    'yonce',
    'zenburn',
  ];

  static final List<String> KEY_MAPS = const [
    'default',
    'emacs',
    'sublime',
    'vim',
  ];

  @override
  Widget build(BuildContext context) {
    return CodeMirrorView(
      key: codeMirrorKey,
      onValue: onValue,
      onCreate: onCreate,
      options: options,
    );
  }
}
